sudo: false
language: go

os:
  - linux
  - osx
go:
  - 1.14.x
  - 1.15.x
# - master
go_import_path: github.com/kataras/iris/v12
env:
 global:
   - GO111MODULE=on
install:
  - go get ./...
script:
  - go test -count=1 -v -cover -race ./...
after_script:
  # examples
  - cd ./_examples
  - go get ./...
  - go test -count=1 -v -cover -race ./...
  - cd ../
