name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version: [1.15, 1.16]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup examples for testing
      working-directory: _examples
      run: ./.github/scripts/setup_examples_test.bash

    - name: Test examples
      working-directory: _examples
      run: go test -v -mod=mod -cover -race ./...
